title: Cardano Atlantic Council Rationale Files
description: Rationale for votes of the Cardano Atlantic Council serving as part of the Interim Constitutional Committee during the Cardano Voltaire Era Bootstrap Phase
